### ISSUE TITLE
 Visdom support?

### ISSUE THREAD

**Issue by huhk-sysu** [ecs-vlc/torchbearer#276]
Will Torchbearer support logging metrics to [Visdom](https://github.com/facebookresearch/visdom) just like what it does to Tensorboard?  Thank you!

**Comment by MattPainter01** [comment]
@huhk-sysu Visdom support is definitely something we'd like to support. We use  [TensorboardX](https://github.com/lanpa/tensorboardX) to support our tensorboard logging and they recently added support for Visdom, so I'll look into it.

**Comment by MattPainter01** [comment]
TensorboardX have just pushed a new release with visdom support so we'll add support soon.
