### ISSUE TITLE
Allow manually control the parameters of tqdm

### ISSUE THREAD

**Issue by huhk-sysu** [ecs-vlc/torchbearer#323]
Currently tqdm can't work correctly on Windows console(see [here](https://github.com/tqdm/tqdm#faq-and-known-issues)).

> Windows consoles often only partially support unicode and thus **[often require explicit ascii=True](https://github.com/tqdm/tqdm/issues/454#issuecomment-33541681)**. This is due to either normal-width unicode characters being incorrectly displayed as "wide", or some unicode characters not rendering.

Please provide a way to control the parameters of tqdm(e.g. set ascii=True). Thanks for your work!

**Comment by ethanwharris** [comment]
Thanks for your issue. Should be fixed when #325 gets merged. In order to pass ascii=True, set verbose=0 in the fit call and from torchbearer.callbacks import Tqdm, then give Tqdm as a callback to the fit call. Hope that helps!
