### ISSUE TITLE
Setting verbosity upon Trial initialization

### ISSUE THREAD

**Issue by kl2792** [ecs-vlc/torchbearer#373]
I was pretty excited to try out the Trial API, and using it has been a lot smoother than most of the other frameworks I've tried. I've run into one small kink, though -- currently, my code looks like this when using the API:

Initializing
``` python
import tqdm.tqdm_notebook as tqdm
trial = tb.Trial(net, torch.optim.Adam(net.parameters()), nn.CrossEntropyLoss(),
                 metrics=['acc', 'loss'], callbacks=[
                     tb.callbacks.Tqdm(tqdm_module=tqdm)
                 ]).to('cuda')
trial.with_generators(trL, val_generator=deL)
```

Replaying (before training)
``` python
trial.replay(callbacks=[tb.callbacks.Tqdm(tqdm_module=tqdm)], verbose=0)
```

Training
``` python
trial.run(epochs=5, verbose=0)
```

Evaluating
``` python
trial.evaluate(verbose=0)
```

The `verbose` option is necessary for all calls to prevent the Jupyter notebook issue #305 from reappearing, and in the `replay` method, `callbacks` is required.

Do you think a printing callback set upon initialization for each instance is a good idea?

**Comment by ethanwharris** [comment]
This seems like a good idea as it would make code cleaner. I can't think of any use cases where you would want different verbose levels. @MattPainter01 any thoughts? Perhaps we have a flag in both so that you can override the global setting?
