### ISSUE TITLE
Trial replaying

### ISSUE THREAD

**Issue by kl2792** [ecs-vlc/torchbearer#375]
Currently, replaying a trial takes ~2-4 seconds per epoch (I'm using a hand-made Tqdm module for Jupyter, so the output below may look a bit different):

```0/5(t): 100%| 1050/1050 [00:02<00:00, 532.58it/s] - running_acc: 0.966 - running_loss: 0.107 - acc: 0.970 - acc_std: 0.172 - loss: 0.106 - loss_std: 0.124
0/5(v): 100%| 263/263 [00:00<00:00, 605.24it/s] - val_acc: 0.962 - val_acc_std: 0.190 - val_loss: 0.164 - val_loss_std: 0.186
1/5(t): 100%| 1050/1050 [00:03<00:00, 395.73it/s] - running_acc: 0.961 - running_loss: 0.153 - acc: 0.973 - acc_std: 0.162 - loss: 0.102 - loss_std: 0.132
1/5(v): 100%| 263/263 [00:01<00:00, 396.25it/s] - val_acc: 0.964 - val_acc_std: 0.187 - val_loss: 0.156 - val_loss_std: 0.176
2/5(t): 100%| 1050/1050 [00:03<00:00, 377.02it/s] - running_acc: 0.966 - running_loss: 0.124 - acc: 0.973 - acc_std: 0.163 - loss: 0.095 - loss_std: 0.124
2/5(v): 100%| 263/263 [00:01<00:00, 300.80it/s] - val_acc: 0.967 - val_acc_std: 0.178 - val_loss: 0.143 - val_loss_std: 0.160
3/5(t): 100%| 1050/1050 [00:04<00:00, 294.61it/s] - running_acc: 0.976 - running_loss: 0.083 - acc: 0.973 - acc_std: 0.161 - loss: 0.092 - loss_std: 0.117
3/5(v): 100%| 263/263 [00:01<00:00, 304.99it/s] - val_acc: 0.968 - val_acc_std: 0.175 - val_loss: 0.144 - val_loss_std: 0.178
4/5(t): 100%| 1050/1050 [00:03<00:00, 405.98it/s] - running_acc: 0.978 - running_loss: 0.088 - acc: 0.973 - acc_std: 0.163 - loss: 0.098 - loss_std: 0.131
4/5(v): 100%| 263/263 [00:01<00:00, 421.27it/s] - val_acc: 0.966 - val_acc_std: 0.182 - val_loss: 0.158 - val_loss_std: 0.177
<torchbearer.trial.Trial at 0x7f1dc6e7d4a8>
```
Do you think it'd be possible to do something like `self._loader.update(len(<dataloader>))` in the printing callback on every epoch to avoid the delay?

Thanks!

**Comment by MattPainter01** [comment]
Currently we track how many steps were performed in the run call and call all the callback methods that would be called in the run, including, for example, on_sample once per batch/step. This is so that any callbacks that might update each batch can still do so in a replay.

We'd like to keep this behaviour but I see no reason we can't add a flag that tells the replay method to only call one batch worth of calls. How does this sound @ethanwharris @kl2792 ?

**Comment by kl2792** [comment]
@MattPainter01 Sorry about the late reply, things have been hectic recently. That sounds great; thank you!
