### ISSUE TITLE
Ordering of with_generators arguments

### ISSUE THREAD

**Issue by kl2792** [ecs-vlc/torchbearer#376]
I hope I'm not being a nuisance by putting in an issue for this, but I was wondering if I could put in a PR for the argument ordering of `with_generators` to make it consistent with `for_steps`.

Currently, to load generators, I have to write:

``` python
trial.with_generators(trL, val_generator=deL, test_generator=teL)
```

It would be nice if I could instead write the following, especially since there's already a `for_steps` function that take in the `train_steps`, `val_steps`, and `test_steps` arguments in between the `generator` arguments:

``` python
trial.with_generators(trL, deL, teL)
```

Please let me know if this sounds reasonable, and again, I hope I'm not being a bother by making this suggestion.

**Comment by ethanwharris** [comment]
That sounds reasonable, arguments should ideally be consistent with the for_steps method. Happy for you to open a PR :)
