### ISSUE TITLE
Model checkpointers save_weights_only

### ISSUE THREAD

**Issue by ethanwharris** [ecs-vlc/torchbearer#505]
As per the discussion in #504 it would be good if the checkpointers had an option to just save the model state dict, rather than the trial one. Not sure what the argument should be, something like save_model_only / save_weights_only? @dorukhansergin @MattPainter01 any thoughts on this?

**Comment by dorukhansergin** [comment]
I'd suggest `save_model_params_only` for two reasons:

1. It's better if the documentation refers to [PyTorch's documentation piece about the issue](https://pytorch.org/docs/stable/notes/serialization.html). There, they use the following phrase to identify the method:

> The first (recommended) saves and loads only the model parameters

2. `save_model_only` is vague in terms of what the scope of model is while `save_weights_only` discards the fact that weight derivatives are also saved (correct me if I'm wrong about this).

**Comment by ethanwharris** [comment]
@dorukhansergin agreed, save_model_params_only is much clearer / more transparent to the user, lets go with that

**Comment by ethanwharris** [comment]
Closed by #508
